project:
  type: website
  output-dir: ../../_book/slides

website:
  title: "CS329H Slides"

format:
  revealjs:
    theme: serif
    slide-number: true
    logo: sail-logo.jpg
    transition: slide
    auto-animate: true
    number-sections: false
    title-slide-attributes:
      data-background-color: "#f5f5f5"
    css: latex-font.css
    math: mathjax
    width: 1280
    height: 720
    margin: 0.1
    center: false
